Implementing the new '@rocket.chat/ui-kit' UI components
RocketChat/Apps.ClickUp pull request #19
Opened 2023-04-04 19:06 UTC by haemza30

This pull request includes several changes to Apps.ClickUp application. Here is a summary of changes made :

1. Updated the rocket.chat/apps-engine to "v1.37.0".
2. Implemented the new "@rocket.chat/ui-kit" block classes, which will allow for greater customization of the application's UI.
3. Replaced all instances of "openModalView" with "openSurfaceView" to maintain consistency with the new naming convention.
4. Replaced all instances of "updateModalView" with "updateSurfaceView" to maintain consistency with the new naming convention.
5. Implemented a custom "blockBuilder" method for creating blocks and block elements.
6. Fixed linting.

2023-04-04 22:46 UTC, mustafahasankhan commented
Woah! Thanks for this, amazed to see such grand contribution.
Can you please resolve the merge conflicts and also share a video recording?

2023-04-05 10:50 UTC, mustafahasankhan commented on ClickUpApp.ts
> +        await connect_user_to_clickup_uid(read, persistence, userData.data.user.id, user.id);
Please change this to persists userasync

2023-04-05 10:53 UTC, mustafahasankhan requested changes
Please see the comment and submit the video recording.

2023-04-10 10:20 UTC, haemza30 commented
I have made the requested changes and Fixed minor issues.

Below are the video recordings 

1. Importing workspaces from ClickUp:
[Screencast from 10-04-23 03:41:29 PM IST.webm](https://user-images.githubusercontent.com/85013735/230882528-3135207b-268f-42ef-b7f8-68b1fa3f4598.webm)

2. Task Management
[Screencast from 10-04-23 02:58:45 PM IST.webm](https://user-images.githubusercontent.com/85013735/230882567-6b55c52a-3108-45f8-81d2-f30823c5f141.webm)

2023-04-10 10:45 UTC, mustafahasankhan commented on src/lib/const.ts
> +    return `${ApiBaseUrl}/${ApiVersion.V2}/space/${ApiEndpoint.FoldersOf(spaceId)}`;
Please change space to ${ApiEndpoint.Space}

2023-04-10 10:46 UTC, mustafahasankhan commented
LGTM, thanks!

2023-04-10 10:46 UTC, merged